approvedGitRepositories:
  - "https://github.com/madfish-solutions/jitsu-js.git"
  - "https://github.com/madfish-solutions/react-native-cloud-fs.git"
  - "https://github.com/madfish-solutions/react-native-scrypt.git"
  - "https://github.com/madfish-solutions/react-native-randombytes.git"

enableScripts: true
nodeLinker: node-modules
npmMinimalAgeGate: 7d
npmPreapprovedPackages:
  - "brace-expansion@1.1.18"
  - "brace-expansion@2.1.4"
