export enum AddressValidationErrorEnum {
  TRON_NETWORK_ADDRESS = 'TRON_NETWORK_ADDRESS',
  EVM_NETWORK_ADDRESS = 'EVM_NETWORK_ADDRESS',
  BTC_NETWORK_ADDRESS = 'BTC_NETWORK_ADDRESS',
  INVALID_ADDRESS = 'INVALID_ADDRESS'
}
