name: Secrets setup

description: Writes secrets

runs:
  using: 'composite'
  steps:
    - name: Create .env file
      shell: bash
      run: |
        cat << EOF > .env
        READ_ONLY_SIGNER_PUBLIC_KEY=${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY }}
        READ_ONLY_SIGNER_PUBLIC_KEY_HASH=${{ secrets.READ_ONLY_SIGNER_PUBLIC_KEY_HASH }}
        TEMPLE_WALLET_API=${{ secrets.TEMPLE_WALLET_API }}
        SEGMENT_ANALYTICS_KEY=${{ secrets.SEGMENT_ANALYTICS_KEY }}
        TEMPLE_WALLET_EXOLIX_API_KEY=${{ secrets.TEMPLE_WALLET_EXOLIX_API_KEY }}
        TEMPLE_WALLET_EVERSTAKE_API_KEY=${{ secrets.TEMPLE_WALLET_EVERSTAKE_API_KEY }}
        TEMPLE_WALLET_EVERSTAKE_LINK_ID=${{ secrets.TEMPLE_WALLET_EVERSTAKE_LINK_ID }}
        TEMPLE_WALLET_UTORG_SID=${{ secrets.TEMPLE_WALLET_UTORG_SID }}
        EOF

    - name: Write secrets to google-services.json
      shell: bash
      run: |
        cat << EOF > ./android/app/google-services.json
        ${{ secrets.FIREBASE_GOOGLE_SERVICE_ANDROID }}
        EOF

    - name: Write secrets to GoogleService-Info.plist
      shell: bash
      run: |
        cat << EOF > ./ios/GoogleService-Info.plist
        ${{ secrets.FIREBASE_GOOGLE_SERVICE_IOS }}
        EOF
