export enum ScanQrCodeAnalyticsEvents {
  SCAN_QR_CODE_ZERO_BALANCE = 'SCAN_QR_CODE_ZERO_BALANCE',
  SCAN_QR_CODE_HANDLE_ERROR = 'SCAN_QR_CODE_HANDLE_ERROR',
  SCAN_QR_CODE_DATA_IGNORED = 'SCAN_QR_CODE_DATA_IGNORED',
  SCAN_QR_CODE_INVALID_QR_CODE = 'SCAN_QR_CODE_INVALID_QR_CODE'
}
