export enum IconNameEnum {
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  Download = 'Download',
  PlusSquare = 'PlusSquare',
  XCircle = 'XCircle',
  ShoppingCard = 'ShoppingCard',
  EyeClosedBold = 'EyeClosedBold',
  EyeOpenBold = 'EyeOpenBold',
  XtzWallet = 'XtzWallet',
  Settings = 'Settings',
  SoonBadge = 'SoonBadge',
  Close = 'Close',
  XtzToken = 'XtzToken',
  TzBtcToken = 'TzBtcToken',
  UsdTzToken = 'UsdTzToken',
  EthTzToken = 'EthTzToken',
  KUsdToken = 'KUsdToken',
  BlndToken = 'BlndToken',
  StkrToken = 'StkrToken',
  Share = 'Share',
  Copy = 'Copy',
  Tag = 'Tag'
}
