/* (!) Numeric Separators (underscores, as in `1_000`) are not supported */

const BLOCK_DURATION = 15000;

const METADATA_SYNC_INTERVAL = 4 * BLOCK_DURATION;

export const TOKENS_SYNC_INTERVAL = METADATA_SYNC_INTERVAL;

export const BALANCES_SYNC_INTERVAL = BLOCK_DURATION;

export const MARKET_SYNC_INTERVAL = 4 * BLOCK_DURATION;

export const SELECTED_BAKER_SYNC_INTERVAL = METADATA_SYNC_INTERVAL;

export const ONE_MINUTE = 60000;

export const PROMO_SYNC_INTERVAL = ONE_MINUTE;

const LONG_INTERVAL = 5 * ONE_MINUTE;

export const RATES_SYNC_INTERVAL = LONG_INTERVAL;

export const NOTIFICATIONS_SYNC_INTERVAL = LONG_INTERVAL;

export const COLLECTIBLES_DETAILS_SYNC_INTERVAL = LONG_INTERVAL;
