/* (!) Numeric Separators (underscores, as in `1_000`) are not supported */

export const BLOCK_DURATION = 15000;

export const MARKET_SYNC_INTERVAL = 4 * BLOCK_DURATION;

export const SELECTED_BAKER_SYNC_INTERVAL = 2 * BLOCK_DURATION;

export const ONE_MINUTE = 60000;

export const PROMO_SYNC_INTERVAL = ONE_MINUTE;

const LONG_INTERVAL = 5 * ONE_MINUTE;

export const RATES_SYNC_INTERVAL = LONG_INTERVAL;

export const NOTIFICATIONS_SYNC_INTERVAL = LONG_INTERVAL;

export const COLLECTIBLES_DETAILS_SYNC_INTERVAL = LONG_INTERVAL;

export const APR_REFRESH_INTERVAL = 30 * ONE_MINUTE;
