import { BakerRewardInterface } from './baker-reward.interface';

export const mockBakerReward: BakerRewardInterface = {
  cycle: 970,
  baker: {
    alias: 'Everstake',
    address: 'tz1aRoaRhSpRYvFdyvgWLL6TGyRoGF51wDjM'
  },
  delegatedBalance: 10622699,
  bakerRewards: {
    ownDelegatedBalance: 81924145796,
    externalDelegatedBalance: 24606129640117,
    ownStakedBalance: 6200770771769,
    externalStakedBalance: 4617831939722,
    bakingPower: 19047953973462,
    totalBakingPower: 407210747682774,
    expectedBlocks: 505,
    futureBlocks: 511,
    futureBlockRewards: 2499822731,
    blocks: 0,
    blockRewardsDelegated: 0,
    blockRewardsStakedOwn: 0,
    blockRewardsStakedEdge: 0,
    blockRewardsStakedShared: 0,
    missedBlocks: 0,
    missedBlockRewards: 0,
    expectedAttestations: 3536314,
    futureAttestations: 3531967,
    futureAttestationRewards: 2468347172,
    attestations: 0,
    attestationRewardsDelegated: 0,
    attestationRewardsStakedOwn: 0,
    attestationRewardsStakedEdge: 0,
    attestationRewardsStakedShared: 0,
    missedAttestations: 0,
    missedAttestationRewards: 0,
    blockFees: 0,
    missedBlockFees: 0,
    doubleBakingRewards: 0,
    doubleBakingLostStaked: 0,
    doubleBakingLostUnstaked: 0,
    doubleBakingLostExternalStaked: 0,
    doubleBakingLostExternalUnstaked: 0,
    vdfRevelationRewardsDelegated: 0,
    vdfRevelationRewardsStakedOwn: 0,
    vdfRevelationRewardsStakedEdge: 0,
    vdfRevelationRewardsStakedShared: 0,
    nonceRevelationRewardsDelegated: 0,
    nonceRevelationRewardsStakedOwn: 0,
    nonceRevelationRewardsStakedEdge: 0,
    nonceRevelationRewardsStakedShared: 0,
    nonceRevelationLosses: 0,
    doubleEndorsingRewards: 0,
    doubleEndorsingLostStaked: 0,
    doubleEndorsingLostUnstaked: 0,
    doubleEndorsingLostExternalStaked: 0,
    doubleEndorsingLostExternalUnstaked: 0,
    doublePreendorsingRewards: 0,
    doublePreendorsingLostStaked: 0,
    doublePreendorsingLostUnstaked: 0,
    doublePreendorsingLostExternalStaked: 0,
    doublePreendorsingLostExternalUnstaked: 0
  }
};
