# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Build to Play Store Alpha track"
  lane :alpha do
    increment_version_code( version_code: ENV["BUILD_NUMBER"], gradle_file_path: "app/build.gradle")
    releaseFilePath = File.join(Dir.pwd, "..", "app/temple-wallet.keystore")
    gradle(task: 'clean')
    gradle(
      task: 'app:assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => ENV["SIGNING_PASSWORD"],
        "android.injected.signing.key.alias" => "temple-wallet-alias",
        "android.injected.signing.key.password" => ENV["SIGNING_PASSWORD"],
      }
    )
    upload_to_play_store(
      track: 'alpha'
    )
  end
end
