name: Environment setup
description: Basic environment setup
runs:
  using: 'composite'
  steps:
    - name: Setup Node 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Get branch name
      uses: EthanSK/git-branch-name-action@v1

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash

    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install
      shell: bash
