name: Code quality

on:
  pull_request:

jobs:
  code-quality:
    name: Checks if ts, lint & unit tests works
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Repository setup
        uses: ./.github/workflows/repository-setup

      - name: Check TypeScript
        run: yarn ts && yarn ts:e2e

      - name: Find deadcode
        run: yarn find-deadcode

      - name: Check ESLint
        run: yarn lint

      - name: Run Unit tests
        run: yarn test

